# Agent CLI Startup Script — agent-engram
#
# Sets workspace-local directories so that AI agent state (memories,
# checkpoints, database) is scoped to this workspace and git-visible.
#
# Activate the section matching your AI CLI tool.
# To switch tools, comment out the active section and uncomment another.
#
# Generated by autoharness. Re-run install or tune to regenerate.

# ── GitHub Copilot CLI ──────────────────────────────────────────────────────
# COPILOT_HOME redirects the Copilot CLI database and memory to a workspace-
# local directory. This keeps agent state visible in git and isolated per
# project rather than shared across all workspaces.
#
# This script does NOT install or refresh Auto-MergeInstall / Auto-Tune.
# Register those globally with `autoharness setup-copilot-cli`.
# Re-run that setup command after upgrading autoharness so updated agent and
# skill files are recopied into the standard Copilot CLI config directory.
#
# COPILOT_EXE_PATH must be an executable path only (no arguments).
# Set ai_tools.copilot_cli.exe_path in .autoharness/config.yaml if copilot
# is not on PATH, then re-run autoharness install or tune.
#
if (-not $env:COPILOT_HOME) { $env:COPILOT_HOME = Join-Path $PSScriptRoot ".copilot" }
# if (-not $env:ENGRAM_DATA_DIR) { $env:ENGRAM_DATA_DIR = Join-Path $PSScriptRoot ".engram" }   # Uncomment when the agent-engram capability pack is active
if (-not $env:GITHUB_TOKEN) {
    if (Get-Command gh -ErrorAction SilentlyContinue) {
        $env:GITHUB_TOKEN = (gh auth token)
    }
}
$copilotExe = if ($env:COPILOT_EXE_PATH) { $env:COPILOT_EXE_PATH } else { "copilot" }
if (-not (Test-Path -LiteralPath $copilotExe -PathType Leaf) -and ($copilotExe -ne "copilot")) {
    throw "COPILOT_EXE_PATH ('$copilotExe') must be a path to the Copilot executable only (no arguments). Update ai_tools.copilot_cli.exe_path in .autoharness/config.yaml."
}
& $copilotExe @args

# ── Claude Code ─────────────────────────────────────────────────────────────
# Uncomment to run Claude Code with workspace-local state directories.
# CLAUDE_CONFIG_DIR redirects Claude's config and history to the workspace.
# Verify that your installed version of Claude Code supports this env variable.
#
# $env:CLAUDE_CONFIG_DIR = ".\.claude"
# claude

# ── OpenAI Codex / Agents ────────────────────────────────────────────────────
# Uncomment to run Codex with a workspace-local API key file.
#
# $env:OPENAI_API_KEY = (Get-Content .openai-token -Raw).Trim()
# codex
