//! Integration tests for hydration (T058) and dehydration with comment
//! preservation (T059) — User Story 3, Git-Backed Persistence.

use std::fs;
use std::sync::Arc;

use chrono::Utc;
use serde_json::json;
use surrealdb::Surreal;
use surrealdb::engine::local::SurrealKv;
use tokio::test;

use t_mem::config::StaleStrategy;
use t_mem::db::queries::Queries;
use t_mem::db::schema;
use t_mem::models::graph::DependencyType;
use t_mem::models::task::{Task, TaskStatus};
use t_mem::server::state::AppState;
use t_mem::services::dehydration::{self, SCHEMA_VERSION};
use t_mem::services::hydration::{hydrate_into_db, hydrate_workspace};
use t_mem::tools;

/// Helper: create an embedded SurrealDB isolated to a temp directory.
async fn test_db(dir: &std::path::Path) -> Queries {
    let db = Surreal::new::<SurrealKv>(dir.to_str().unwrap())
        .await
        .expect("embedded db");
    db.use_ns("test").use_db("hydration").await.expect("ns/db");
    db.query(schema::DEFINE_TASK).await.expect("schema task");
    db.query(schema::DEFINE_CONTEXT)
        .await
        .expect("schema context");
    db.query(schema::DEFINE_RELATIONSHIPS)
        .await
        .expect("schema rels");
    Queries::new(db)
}

fn make_task(id: &str, status: TaskStatus, desc: &str) -> Task {
    let now = Utc::now();
    Task {
        id: id.to_string(),
        title: format!("Task {id}"),
        status,
        work_item_id: None,
        description: desc.to_string(),
        context_summary: None,
        created_at: now,
        updated_at: now,
    }
}

// ─── T058: Integration test for hydration from .tmem/ files ─────────────────

#[test]
async fn hydrate_from_tmem_files_loads_tasks_into_db() {
    let workspace = tempfile::tempdir().expect("workspace tempdir");
    let db_dir = tempfile::tempdir().expect("db tempdir");

    // Create .git/ so the workspace looks valid
    fs::create_dir(workspace.path().join(".git")).expect("create .git");

    // Create .tmem/ with tasks.md
    let tmem_dir = workspace.path().join(".tmem");
    fs::create_dir_all(&tmem_dir).expect("create .tmem");
    fs::write(
        tmem_dir.join("tasks.md"),
        r#"# Tasks

## task:t1

---
id: task:t1
title: First task
status: in_progress
created_at: 2026-02-05T10:00:00+00:00
updated_at: 2026-02-05T14:30:00+00:00
---

First task description.

## task:t2

---
id: task:t2
title: Second task
status: todo
created_at: 2026-02-05T11:00:00+00:00
updated_at: 2026-02-05T11:00:00+00:00
---

Second task description.
"#,
    )
    .expect("write tasks.md");

    // Create graph.surql with a dependency
    fs::write(
        tmem_dir.join("graph.surql"),
        r#"-- Generated by T-Mem
RELATE task:t2->depends_on->task:t1 SET type = 'hard_blocker';
"#,
    )
    .expect("write graph.surql");

    // Write version
    fs::write(tmem_dir.join(".version"), SCHEMA_VERSION).expect("write version");

    // Hydrate summary (lightweight)
    let summary = hydrate_workspace(workspace.path())
        .await
        .expect("hydrate summary");
    assert_eq!(summary.task_count, 2);

    // Hydrate into DB
    let queries = test_db(db_dir.path()).await;
    let result = hydrate_into_db(workspace.path(), &queries)
        .await
        .expect("hydrate into db");
    assert_eq!(result.tasks_loaded, 2);
    assert_eq!(result.edges_loaded, 1);

    // Verify tasks are in DB
    let t1 = queries.get_task("t1").await.expect("get t1");
    assert!(t1.is_some());
    let t1 = t1.unwrap();
    assert_eq!(t1.title, "First task");
    assert_eq!(t1.status, TaskStatus::InProgress);
    assert!(t1.description.contains("First task description"));

    let t2 = queries.get_task("t2").await.expect("get t2");
    assert!(t2.is_some());
    assert_eq!(t2.unwrap().status, TaskStatus::Todo);

    // Verify dependency edge
    let deps = queries.dependencies_of("t2").await.expect("deps of t2");
    assert_eq!(deps.len(), 1);
    assert_eq!(deps[0].to, "t1");
    assert_eq!(deps[0].kind, DependencyType::HardBlocker);
}

#[test]
async fn hydrate_empty_workspace_creates_tmem_dir() {
    let workspace = tempfile::tempdir().expect("workspace");
    fs::create_dir(workspace.path().join(".git")).expect(".git");

    let summary = hydrate_workspace(workspace.path()).await.expect("hydrate");
    assert_eq!(summary.task_count, 0);
    assert!(workspace.path().join(".tmem").exists());
}

// ─── T059: Integration test for dehydration preserving comments ─────────────

#[test]
async fn dehydrate_preserves_user_comments_in_tasks_md() {
    let workspace = tempfile::tempdir().expect("workspace");
    let db_dir = tempfile::tempdir().expect("db");

    fs::create_dir(workspace.path().join(".git")).expect(".git");

    // Create existing tasks.md with user comments
    let tmem_dir = workspace.path().join(".tmem");
    fs::create_dir_all(&tmem_dir).expect("create .tmem");
    fs::write(
        tmem_dir.join("tasks.md"),
        r#"# Tasks

<!-- Project notes: this is a critical module -->

## task:t1

---
id: task:t1
title: Auth task
status: todo
created_at: 2026-02-05T10:00:00+00:00
updated_at: 2026-02-05T10:00:00+00:00
---

Implement authentication.

<!-- NOTE: Must support OAuth2 -->

"#,
    )
    .expect("write old tasks.md");

    // Insert the same task into DB with updated status
    let queries = test_db(db_dir.path()).await;
    let task = Task {
        id: "t1".to_string(),
        title: "Auth task".to_string(),
        status: TaskStatus::InProgress,
        work_item_id: None,
        description: "Implement authentication.".to_string(),
        context_summary: None,
        created_at: Utc::now(),
        updated_at: Utc::now(),
    };
    queries.upsert_task(&task).await.expect("upsert");

    // Dehydrate
    let result = dehydration::dehydrate_workspace(&queries, workspace.path())
        .await
        .expect("dehydrate");
    assert_eq!(result.tasks_written, 1);
    assert!(result.files_written.contains(&".tmem/tasks.md".to_string()));
    assert!(
        result
            .files_written
            .contains(&".tmem/graph.surql".to_string())
    );

    // Read back and verify
    let content = fs::read_to_string(tmem_dir.join("tasks.md")).expect("read tasks.md");

    // File header preserved
    assert!(
        content.contains("<!-- Project notes: this is a critical module -->"),
        "file header comment should be preserved"
    );

    // Status updated
    assert!(
        content.contains("status: in_progress"),
        "status should be updated to in_progress"
    );

    // User comment preserved (FR-012)
    assert!(
        content.contains("<!-- NOTE: Must support OAuth2 -->"),
        "user HTML comment should be preserved"
    );

    // Version file written
    let version = fs::read_to_string(tmem_dir.join(".version")).expect("read version");
    assert_eq!(version, SCHEMA_VERSION);

    // Lastflush written
    assert!(tmem_dir.join(".lastflush").exists());
}

#[test]
async fn dehydrate_round_trip_preserves_data() {
    let workspace = tempfile::tempdir().expect("workspace");
    let db_dir = tempfile::tempdir().expect("db");

    fs::create_dir(workspace.path().join(".git")).expect(".git");

    let queries = test_db(db_dir.path()).await;

    // Insert tasks and edges
    let t1 = make_task("t1", TaskStatus::InProgress, "First task");
    let t2 = make_task("t2", TaskStatus::Todo, "Second task");
    queries.upsert_task(&t1).await.expect("upsert t1");
    queries.upsert_task(&t2).await.expect("upsert t2");
    queries
        .create_dependency("t2", "t1", DependencyType::HardBlocker)
        .await
        .expect("dep t2->t1");

    // Dehydrate to files
    let result = dehydration::dehydrate_workspace(&queries, workspace.path())
        .await
        .expect("dehydrate");
    assert_eq!(result.tasks_written, 2);
    assert_eq!(result.edges_written, 1);

    // Clear DB and re-hydrate
    queries.clear_all_data().await.expect("clear");
    let all = queries.all_tasks().await.expect("all tasks");
    assert!(all.is_empty(), "DB should be empty after clear");

    let hydrated = hydrate_into_db(workspace.path(), &queries)
        .await
        .expect("re-hydrate");
    assert_eq!(hydrated.tasks_loaded, 2);
    assert_eq!(hydrated.edges_loaded, 1);

    // Verify round-trip
    let restored_t1 = queries.get_task("t1").await.expect("get t1");
    assert!(restored_t1.is_some());
    assert_eq!(restored_t1.unwrap().status, TaskStatus::InProgress);
}

// ─── T115/T116/T117: Stale strategy integration tests ─────────────────────

#[test]
async fn flush_state_warns_on_stale_files_in_warn_mode() {
    let workspace = tempfile::tempdir().expect("workspace");
    fs::create_dir(workspace.path().join(".git")).expect("create .git");

    let tmem_dir = workspace.path().join(".tmem");
    fs::create_dir_all(&tmem_dir).expect("create .tmem");
    fs::write(
        tmem_dir.join("tasks.md"),
        r#"# Tasks

## task:t1

---
id: task:t1
title: Initial
status: todo
created_at: 2026-02-05T10:00:00+00:00
updated_at: 2026-02-05T10:00:00+00:00
---

Initial description.
"#,
    )
    .expect("write tasks");

    let state = Arc::new(AppState::with_stale_strategy(10, StaleStrategy::Warn));
    let path = workspace.path().to_string_lossy().to_string();

    tools::dispatch(
        state.clone(),
        "set_workspace",
        Some(json!({ "path": path })),
    )
    .await
    .expect("set_workspace");

    // External modification after hydration
    fs::write(tmem_dir.join("tasks.md"), "# Tasks\n\n<!-- changed -->\n").expect("modify tasks");

    let result = tools::dispatch(state.clone(), "flush_state", None)
        .await
        .expect("flush_state should warn, not fail");

    let warnings = result
        .get("warnings")
        .and_then(|v| v.as_array())
        .expect("warnings array");
    assert!(
        warnings
            .iter()
            .filter_map(|v| v.as_str())
            .any(|w| w.contains("StaleWorkspace")),
        "should include stale workspace warning",
    );
}

#[test]
async fn flush_state_rehydrates_before_writing_when_configured() {
    let workspace = tempfile::tempdir().expect("workspace");
    fs::create_dir(workspace.path().join(".git")).expect("create .git");

    let tmem_dir = workspace.path().join(".tmem");
    fs::create_dir_all(&tmem_dir).expect("create .tmem");
    fs::write(
        tmem_dir.join("tasks.md"),
        r#"# Tasks

## task:t1

---
id: task:t1
title: Initial
status: todo
created_at: 2026-02-05T10:00:00+00:00
updated_at: 2026-02-05T10:00:00+00:00
---

Initial description.
"#,
    )
    .expect("write tasks");

    let state = Arc::new(AppState::with_stale_strategy(10, StaleStrategy::Rehydrate));
    let path = workspace.path().to_string_lossy().to_string();

    tools::dispatch(
        state.clone(),
        "set_workspace",
        Some(json!({ "path": path })),
    )
    .await
    .expect("set_workspace");

    // External modification after hydration: change title and body
    fs::write(
        tmem_dir.join("tasks.md"),
        r#"# Tasks

## task:t1

---
id: task:t1
title: Modified Title
status: todo
created_at: 2026-02-05T10:00:00+00:00
updated_at: 2026-02-05T10:00:00+00:00
---

Modified description from disk.
"#,
    )
    .expect("modify tasks");

    let result = tools::dispatch(state.clone(), "flush_state", None)
        .await
        .expect("flush_state should rehydrate and succeed");

    let warnings = result
        .get("warnings")
        .and_then(|v| v.as_array())
        .expect("warnings array");
    assert!(warnings.is_empty(), "rehydrate mode should not warn");

    let flushed = fs::read_to_string(tmem_dir.join("tasks.md")).expect("read tasks.md");
    assert!(
        flushed.contains("Modified Title"),
        "external changes should be preserved after rehydrate + flush"
    );
    assert!(flushed.contains("Modified description from disk."));
}

#[test]
async fn flush_state_fails_on_stale_files_in_fail_mode() {
    let workspace = tempfile::tempdir().expect("workspace");
    fs::create_dir(workspace.path().join(".git")).expect("create .git");

    let tmem_dir = workspace.path().join(".tmem");
    fs::create_dir_all(&tmem_dir).expect("create .tmem");
    fs::write(tmem_dir.join("tasks.md"), "# Tasks\n").expect("write tasks");

    let state = Arc::new(AppState::with_stale_strategy(10, StaleStrategy::Fail));
    let path = workspace.path().to_string_lossy().to_string();

    tools::dispatch(
        state.clone(),
        "set_workspace",
        Some(json!({ "path": path })),
    )
    .await
    .expect("set_workspace");

    // External modification after hydration
    fs::write(tmem_dir.join("tasks.md"), "# Tasks\n<!-- changed -->\n").expect("modify tasks");

    let err = tools::dispatch(state.clone(), "flush_state", None)
        .await
        .expect_err("stale files should trigger failure");

    let payload = err.to_response();
    assert_eq!(payload.error.code, t_mem::errors::codes::STALE_WORKSPACE);
}
