//! Integration tests for installer registry auto-detection (T017).
//!
//! Validates scenarios: S002, S013.

use std::fs;
use tempfile::TempDir;

use engram::services::registry::{load_registry, parse_registry_yaml};

/// S002: Auto-detect generates registry with entries for src, tests, specs, docs.
#[test]
fn auto_detect_generates_registry_for_standard_dirs() {
    let dir = TempDir::new().unwrap();
    let ws = dir.path();

    // Create standard directories.
    fs::create_dir_all(ws.join("src")).unwrap();
    fs::create_dir_all(ws.join("tests")).unwrap();
    fs::create_dir_all(ws.join("specs")).unwrap();
    fs::create_dir_all(ws.join("docs")).unwrap();
    fs::create_dir_all(ws.join(".engram")).unwrap();

    // Simulate what the installer does: call the auto-detection logic.
    // Since we can't call install() without an exe, we test the YAML
    // that would be generated by scanning for known directories.
    let known_dirs: &[(&str, &str, Option<&str>)] = &[
        ("src", "code", Some("rust")),
        ("tests", "tests", Some("rust")),
        ("specs", "spec", Some("markdown")),
        ("docs", "docs", Some("markdown")),
    ];

    let mut entries = Vec::new();
    for &(dir_name, content_type, language) in known_dirs {
        if ws.join(dir_name).is_dir() {
            if let Some(lang) = language {
                entries.push(format!(
                    "  - type: {content_type}\n    language: {lang}\n    path: {dir_name}\n"
                ));
            } else {
                entries.push(format!("  - type: {content_type}\n    path: {dir_name}\n"));
            }
        }
    }

    let yaml = format!("sources:\n{}", entries.join(""));
    fs::write(ws.join(".engram").join("registry.yaml"), &yaml).unwrap();

    // Verify loading works.
    let config = load_registry(&ws.join(".engram").join("registry.yaml"))
        .expect("load should succeed")
        .expect("config should be Some");

    assert_eq!(config.sources.len(), 4);
    assert_eq!(config.sources[0].content_type, "code");
    assert_eq!(config.sources[0].path, "src");
    assert_eq!(config.sources[1].content_type, "tests");
    assert_eq!(config.sources[2].content_type, "spec");
    assert_eq!(config.sources[3].content_type, "docs");
}

/// S013: No recognizable directories produces empty sources.
#[test]
fn no_recognizable_dirs_produces_empty_sources() {
    let dir = TempDir::new().unwrap();
    let ws = dir.path();
    // Only create a random non-standard directory.
    fs::create_dir_all(ws.join("random")).unwrap();
    fs::create_dir_all(ws.join(".engram")).unwrap();

    // Simulate auto-detection finding nothing.
    let known_dirs: &[&str] = &["src", "tests", "specs", "docs"];
    let any_found = known_dirs.iter().any(|d| ws.join(d).is_dir());
    assert!(!any_found);

    // An empty registry should parse fine.
    let yaml = "sources: []\n";
    let config = parse_registry_yaml(yaml).unwrap();
    assert!(config.sources.is_empty());
}
